export { LEFT_SIDEBAR } from "./Left-sidebar";
export { Search_Bar } from "./Search-bar";
export { Information } from "./Right-sidebar/Informations";
export { Poly_Division } from "./Right-sidebar/PolyclinicDivision";
export { Gender_Patient } from "./Main/GenderPatient";
export { Group_Patient } from "./Main/GroupPatient";
export { Overview } from "./Main/Overview";
export { Patient_Stats } from "./Main/PatientCovidStats";
export { Staff_Info } from "./Main/StaffInfo";
